### ISSUE TITLE
Error when trying to install Aurora Sdk 4.0.1

### ISSUE THREAD

**Issue by Hatemsla** [keygenqt/aurora-cli#10]
When trying to install Aurora error, the installation script crashes:

```shell
aurora-cli sdk install -a
Waiting for a response from the server...
Select version index
1: 5.1.0
2: 5.0.1
3: 5.0.0
4: 4.1.0
5: 4.0.2
6: 4.0.1

Select index: 6
Traceback (most recent call last):
  File "/home/hatemsla/.local/bin/aurora-cli", line 8, in <module>
    sys.exit(main())
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/aurora_cli/src/features/sdk/group_sdk.py", line 76, in install
    installer_url = get_url_sdk_run(version, install_type)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/aurora_cli/src/features/sdk/impl/utils.py", line 68, in get_url_sdk_run
    response = get_request(url_folder)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/aurora_cli/src/support/helper.py", line 268, in get_request
    return requests.get(url, stream=stream)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
````
aurora-cli version:

```shell
aurora-cli --version
aurora-cli, version 2.4.8
```

Other SDKs are being installed successfully
The same story with the psdk

**Comment by keygenqt** [comment]
+

**Comment by keygenqt** [comment]
version 2.5.0

**Comment by Hatemsla** [comment]
In fact, nothing has changed when trying to install sdk or psdk 4.0.1.249 version. By the way, they are not available through the command. I install everything via wsl2 Ubuntu

```bash
hatemsla@Hatemsla:~$ uname -a
Linux Hatemsla 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
hatemsla@Hatemsla:~$ aurora-cli sdk install -a
Waiting for a response from the server...
Select version index
1: 5.1.0
2: 5.0.1
3: 5.0.0
4: 4.1.0
5: 4.0.2
6: 4.0.1

Select index: 6
Traceback (most recent call last):
  File "/home/hatemsla/.local/bin/aurora-cli", line 8, in <module>
    sys.exit(main())
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/aurora_cli/src/features/sdk/group_sdk.py", line 76, in install
    installer_url = get_url_sdk_run(version, install_type)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/aurora_cli/src/features/sdk/impl/utils.py", line 68, in get_url_sdk_run
    response = get_request(url_folder)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/aurora_cli/src/support/helper.py", line 268, in get_request
    return requests.get(url, stream=stream)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/hatemsla/.local/lib/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'None': No scheme supplied. Perhaps you meant https://None?
hatemsla@Hatemsla:~$ aurora-cli psdk install -a
Waiting for a response from the server...
Select version index
1: 5.1.0
2: 5.0.1
3: 5.0.0
4: 4.1.0
5: 4.0.2
6: 4.0.1

Select index: 6
Aurora Platform SDK not found.
Chroot tar.bz2 not found.
hatemsla@Hatemsla:~$ aurora-cli sdk available
Waiting for a response from the server...
Available versions Aurora SDK:
5.1.0
5.0.1
5.0.0
4.1.0
hatemsla@Hatemsla:~$ aurora-cli psdk available
Waiting for a response from the server...
Available versions Aurora Platform SDK:
5.1.0
5.0.1
5.0.0
4.1.0
hatemsla@Hatemsla:~$ aurora-cli --version
aurora-cli, version 2.5.0
hatemsla@Hatemsla:~$ 
```
