### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by arkonsolutions** [keygenqt/aurora-cli#15]
Hello, after the installing by instructins and call "aurora-cli" i get a result:
i am using Windows + WSL (windows subsystem linux)

```
wsa@DESKTOP-FD5GL70:~$ aurora-cli
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/wsa/.local/opt/aurora-cli.pyz/__main__.py", line 3, in <module>
  File "/home/wsa/.local/opt/aurora-cli.pyz/_bootstrap/__init__.py", line 253, in bootstrap
  File "/home/wsa/.local/opt/aurora-cli.pyz/_bootstrap/__init__.py", line 59, in import_string
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/wsa/.shiv/aurora-cli.pyz_779a601e28c72461e712e9b30c4881cf9ea9a873599cd3c1fde6f9391c7f1093/site-packages/aurora_cli/__main__.py", line 22, in 
<module>
    from aurora_cli.src.features.devices.group_device import group_device  # noqa: E402
  File "/home/wsa/.shiv/aurora-cli.pyz_779a601e28c72461e712e9b30c4881cf9ea9a873599cd3c1fde6f9391c7f1093/site-packages/aurora_cli/src/features/devices/group_device.py", line 19, in <module>
    from aurora_cli.src.features.devices.impl.common import common_command, common_run, common_install, common_upload
  File "/home/wsa/.shiv/aurora-cli.pyz_779a601e28c72461e712e9b30c4881cf9ea9a873599cd3c1fde6f9391c7f1093/site-packages/aurora_cli/src/features/devices/impl/common.py", line 20, in <module>
    from aurora_cli.src.support.helper import get_path_files
  File "/home/wsa/.shiv/aurora-cli.pyz_779a601e28c72461e712e9b30c4881cf9ea9a873599cd3c1fde6f9391c7f1093/site-packages/aurora_cli/src/support/helper.py", line 103, in <module>
    def find_path_file(extension: str, path: Path) -> Path | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by arkonsolutions** [comment]
It solved by updating python version to 3.10
https://stackoverflow.com/a/76555873

**Comment by arkonsolutions** [comment]
but, next day, when i call "aurora-cli", then get message "-bash: aurora-cli: command not found"

**Comment by keygenqt** [comment]
https://t.me/aurora_dev/643
