### ISSUE TITLE
Не работает aurora-cli vscode tuning

### ISSUE THREAD

**Issue by marat-yusupov** [keygenqt/aurora-cli#21]
При попытке вызове команды aurora-cli vscode tuning выводится следующее:

```
Расширения для работы с Flutter уже установлены.
Расширения для работы с C++ уже установлены.
Расширения для работы с VS Code уже установлены.
An unexpected error occurred in the application.
```

При вызове с флагом --verbose получаю такую картину:

```
Расширения для работы с Flutter уже установлены.
Расширения для работы с C++ уже установлены.
Расширения для работы с VS Code уже установлены.
Выполнена команда: `code --list-extensions`
Run time seconds: 0.50
chadalen.vscode-jetbrains-icon-theme
dart-code.dart-code
dart-code.flutter
dbaeumer.vscode-eslint
eamodio.gitlens
equinusocio.vsc-material-theme-icons
github.github-vscode-theme
king2021.vnc-extension
lakshits11.horizon-legacy
mesonbuild.mesonbuild
michaelzhou.fleet-theme
ms-ceintl.vscode-language-pack-ru
ms-python.debugpy
ms-python.python
ms-python.vscode-pylance
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.extension-test-runner
rexthedev.flutter-preview
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-russian
twxs.cmake
vscode-icons-team.vscode-icons
webfreak.debug
xaver.clang-format
ybaumes.highlight-trailing-white-spaces
Выполнена команда: `code --list-extensions`
Run time seconds: 0.49
chadalen.vscode-jetbrains-icon-theme
dart-code.dart-code
dart-code.flutter
dbaeumer.vscode-eslint
eamodio.gitlens
equinusocio.vsc-material-theme-icons
github.github-vscode-theme
king2021.vnc-extension
lakshits11.horizon-legacy
mesonbuild.mesonbuild
michaelzhou.fleet-theme
ms-ceintl.vscode-language-pack-ru
ms-python.debugpy
ms-python.python
ms-python.vscode-pylance
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.extension-test-runner
rexthedev.flutter-preview
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-russian
twxs.cmake
vscode-icons-team.vscode-icons
webfreak.debug
xaver.clang-format
ybaumes.highlight-trailing-white-spaces
An unexpected error occurred in the application.
Traceback (most recent call last):
  File "/home/myuspv/.local/bin/aurora-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/myuspv/.local/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuspv/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/myuspv/.local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuspv/.local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuspv/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuspv/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuspv/.local/lib/python3.12/site-packages/aurora_cli/src/cli/vscode/group_vscode.py", line 74, in tuning
    vscode_settings_common()
  File "/home/myuspv/.local/lib/python3.12/site-packages/aurora_cli/src/base/common/groups/vscode/vscode_features.py", line 100, in vscode_settings_common
    config = json.loads(file.read())
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _по умолчанию_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 11 column 5 (char 453)
```

Условия повторения:
1) Ubuntu 24.04 LTS
2) Установить aurora-cli:
`
python3 -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple aurora-cli --break-system-packages
`
3) Вызвать 'aurora-cli vscode tuning'

**Comment by keygenqt** [comment]
Проверил на 22.04 - все ок. На 24.04 ченкну как будет 24.04.1

**Comment by keygenqt** [comment]
Протестировал на 3.0.0 проблемы не обнаружено.
