### ISSUE TITLE
Don`t work adding sudoers on ALT Regular

### ISSUE THREAD

**Issue by neeromeero** [keygenqt/aurora-cli#27]
При вызове команды `aurora-cli psdk sudoers add -v` ответом выводит **An unexpected error occurred in the application.**

```
Traceback (most recent call last):
  File "/home/usertest/.local/bin/aurora-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/usertest/.local/lib/python3/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usertest/.local/lib/python3/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/usertest/.local/lib/python3/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usertest/.local/lib/python3/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usertest/.local/lib/python3/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usertest/.local/lib/python3/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usertest/.local/lib/python3/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/usertest/.local/lib/python3/site-packages/aurora_cli/src/cli/psdk/subgroup_psdk_sudoers.py", line 46, in sudoers_add
    psdk_sudoers_add_common(model)
  File "/home/usertest/.local/lib/python3/site-packages/aurora_cli/src/base/common/groups/psdk/psdk_sudoers_features.py", line 47, in psdk_sudoers_add_common
    if not path.is_file():
           ^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/pathlib.py", line 892, in is_file
    return S_ISREG(self.stat().st_mode)
                   ^^^^^^^^^^^
  File "/usr/lib64/python3.12/pathlib.py", line 840, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/etc/sudoers.d/mer-sdk-chroot'
```

Также после установки flutter при помощи **aurora-cli flutter install** и вызове **flutter-aurora doctor** выдает отсутствие psdk_dir path.

```
[✗] Aurora toolchain - develop for Aurora OS
    ✗ Exception: Necessary to add the path to psdk_dir to the flutter configuration.
      Example: `flutter config --aurora-psdk-dir=$HOME/AuroraPlatformSDK/sdks/aurora_psdk`
      More information about Platform SDK: https://developer.auroraos.ru/doc/software_development/psdk
```
Пытаясь пофиксить при помощи **flutter-aurora config --aurora-psdk-dir=$HOME/AuroraPlatformSDK-5.1.2.10/sdks/aurora_psdk** 
выдаёт **Failed to add sudoers setting for Platform SDK.**

**Comment by keygenqt** [comment]
Нужно проверить sudoers на ALT. Спасибо.

Рекомендованая система для Flutter - Ubuntu.

**Comment by keygenqt** [comment]
Пока так: https://github.com/keygenqt/aurora-cli/commit/a4e9ea42f5e4f42527d25846aff01f3c98e8902e
Фича с sudoers корретктно работат только на Ubuntu.
