### ISSUE TITLE
Ошибка при выполнении команды aurora-cli vscode tuning

### ISSUE THREAD

**Issue by zheleznyakov** [keygenqt/aurora-cli#33]
**Ошибка**
``` aurora-cli vscode tuning ```
выдаёт ошибку

```
╰─ aurora-cli vscode tuning -v
Расширения для работы с Flutter уже установлены.
Расширения для работы с C++ уже установлены.
Расширения для работы с VS Code уже установлены.
Выполнена команда: `code --list-extensions`
Run time seconds: 0.51
dart-code.dart-code
dart-code.flutter
mesonbuild.mesonbuild
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-russian
twxs.cmake
webfreak.debug
ybaumes.highlight-trailing-white-spaces
Выполнена команда: `code --list-extensions`
Run time seconds: 0.48
dart-code.dart-code
dart-code.flutter
mesonbuild.mesonbuild
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
streetsidesoftware.code-spell-checker
streetsidesoftware.code-spell-checker-russian
twxs.cmake
webfreak.debug
ybaumes.highlight-trailing-white-spaces
An unexpected error occurred in the application.
Traceback (most recent call last):
  File "/home/andrey/.local/bin/aurora-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/andrey/.local/lib/python3/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrey/.local/lib/python3/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/andrey/.local/lib/python3/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrey/.local/lib/python3/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrey/.local/lib/python3/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrey/.local/lib/python3/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andrey/.local/lib/python3/site-packages/aurora_cli/src/cli/vscode/group_vscode.py", line 74, in tuning
    vscode_settings_common()
  File "/home/andrey/.local/lib/python3/site-packages/aurora_cli/src/base/common/groups/vscode/vscode_features.py", line 104, in vscode_settings_common
    config = json.loads(file.read())
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/__init__.py", line 346, in loads
    return _по умолчанию_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 6 column 1 (char 163)
```
- ОС: [Alt Gnome Starterkit P11]
- Версия Aurora CLI [например, 3.0.14]

**Comment by keygenqt** [comment]
Ошибка не обнаружена (Alt Gnome Starterkit P11). Попробуйте обновиться до 3.0.16

![Screenshot from 2024-11-06 08-49-05](https://github.com/user-attachments/assets/b13af542-0e9b-4c8a-9e37-db4633fe7d05)
